/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soundtester;

import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 * Panel do przeprowadzenia testu ACR.
 */
public class PanelACR extends javax.swing.JPanel {
    
    /**
     * Liczba osób testujących.
     */
    private final int testers;
    /**
     * Nr osoby testującej, która aktualnie testuje próbkę.
     */
    private int actualTester;
    /**
     * Model tabeli z danymi.
     */
    private DataTableModelACR model;
    /**
     * Nr zaznaczonego wiersza z testowaną próbką.
     */
    private int lastSelectedRow;

    /**
     * 
     * @param samples Lista próbek w postaci ścieżek do plików.
     * @param testers Liczba osób testujących.
     */
    public PanelACR(ArrayList<String> samples, int testers) {
        this.testers = testers;
        this.actualTester = 1;
        this.lastSelectedRow = 0;
        model = new DataTableModelACR(testers);
        model.setValueAt(samples);
        initComponents();
        initTableModel();
        getRowData();
        
        sliderEvaluation.setMajorTickSpacing(1);
        sliderEvaluation.setMinorTickSpacing(1);
        sliderEvaluation.setPaintTicks(true);
        sliderEvaluation.setPaintLabels(true);
    }
    
    /**
     * Ustawienie atrybutów tabeli (np. szerokość kolumn).
     */
    private void initTableModel(){
        int cols = model.getColumnCount();
	TableColumn col;
	col = table.getColumnModel().getColumn(0);
	col.setPreferredWidth(60);
	col.setMaxWidth(60);
	col = table.getColumnModel().getColumn(1);
	col.setPreferredWidth(150);
	col.setMaxWidth(400);
	col = table.getColumnModel().getColumn(2);
	col.setPreferredWidth(200);
	col.setMaxWidth(1000);
        for (int i = 3; i < cols-1; i++) {
            col = table.getColumnModel().getColumn(i);
            col.setPreferredWidth(60);
            col.setMaxWidth(100);
        }
	col = table.getColumnModel().getColumn(cols-1);
	col.setPreferredWidth(60);
	col.setMaxWidth(100);        
        DefaultTableCellRenderer r = new DefaultTableCellRenderer();
        r.setHorizontalAlignment(SwingConstants.RIGHT);// wyrównanie do prawej kolumny oceny
        col.setCellRenderer(r);
        
        
        table.setRowSelectionInterval(0, 0);
    }
    
    /**
     * Akcja po zaznaczeniu wiersza tabeli. Pobiera dane z zaznaczonego wiersza modelu tabeli i wstawia je do odpowiednich kontrolek w panelu edycji.
     */
    private void getRowData() {
        int row = this.table.getSelectedRow();
        if (row > -1) {
            this.actualTester = 1;
            this.labelTester.setText("Tester: 1");
            this.textFieldSampleName.setText((String) model.getValueAt(row, 1));
            Integer evaluation = (Integer) model.getValueAt(row, 3);
            this.sliderEvaluation.setValue((evaluation == null || evaluation == 0) ? 3 : evaluation);
            
            this.model.setValueAt(String.format("%.2f", getAverageEvaluation(lastSelectedRow)), lastSelectedRow, model.getColumnCount()-1);
            this.lastSelectedRow = row;
        }
    }
    
    /**
     * Odtwarzanie dźwięku.
     * @param path Ściażka do pliku/próbki.
     */
    private void play(String path) {
        try {
            AudioPlayer.player.start(new AudioStream(new FileInputStream(path)));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Błąd przy odtwarzaniu próbki", null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * 
     * @param row Indeks zaznaczonego wiersza w tabeli.
     * @return Średnia arytmetyczna ocen wszystkich testerów.
     */
    private float getAverageEvaluation(int row) {
        int result = 0;
        for (int col = 3; col < testers+3; col++) {
            result += (Integer) model.getValueAt(row, col);
        }
        
        return (float) result / (float) testers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldSampleName = new javax.swing.JTextField();
        buttonPlay = new javax.swing.JButton();
        sliderEvaluation = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        buttonAccept = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        labelTester = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jLabel1.setText("Nazwa próbki:");

        textFieldSampleName.setEditable(false);
        textFieldSampleName.setPreferredSize(new java.awt.Dimension(200, 24));

        buttonPlay.setText("Odtwarzaj");
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        sliderEvaluation.setMaximum(5);
        sliderEvaluation.setMinimum(1);
        sliderEvaluation.setPaintLabels(true);
        sliderEvaluation.setValue(3);

        jLabel2.setText("Ocena próbki:");

        buttonAccept.setText("Zatwierdź ocenę");
        buttonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcceptActionPerformed(evt);
            }
        });

        buttonSave.setText("Zapisz wyniki");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        labelTester.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTester.setText("Tester: 1"); // NOI18N
        labelTester.setPreferredSize(new java.awt.Dimension(60, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSampleName, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(buttonSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAccept)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldSampleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonPlay)
                        .addComponent(jLabel2)
                        .addComponent(labelTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAccept))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table.setModel(this.model);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Wybór wiersza z próbką przez użytkownika. Kliknięcie tabeli myszą.
 * @param evt Zdarzenie.
 */
    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        getRowData();
    }//GEN-LAST:event_tableMouseReleased
/**
 * Wybór wiersza z próbką przez użytkownika. Nawigacja przy użyciu klawiatury.
 * @param evt Zdarzenie.
 */
    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        getRowData();
    }//GEN-LAST:event_tableKeyReleased
/**
 * Akcja kliknięcia przycisku odtwarzającego próbkę z wybranego wiersza tabeli.
 * @param evt Zdarzenie.
 */
    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        int row = this.table.getSelectedRow();
        if (row > -1) {
            this.play((String) model.getValueAt(row, 2));
        }
    }//GEN-LAST:event_buttonPlayActionPerformed
/**
 * Akcja kliknięcia przycisku zatwierdzającego ocenę osoby testującej. Zapisuje wynik oceny do modelu tabeli.
 * Sprawdza czy próbka została przetestowana przez wszystkich testerów. Jeśli nie, to przechodzi do następnego testera.
 * Jeśli tak, to sprawdza, czy są jeszcze nieprzetestowane próbki, jeśli tak, to ustawia zaznaczenie kolejnego wiersza tabeli, jeśli nie, to wyświetla stosowny komunikat.
 * @param evt Zdarzenie.
 */
    private void buttonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcceptActionPerformed
        int row = this.table.getSelectedRow();
        int col = 2 + actualTester;
        if (row > -1) {
            int evaluation = this.sliderEvaluation.getValue();
            this.model.setValueAt(evaluation, row, col);
            if (actualTester == testers) {
                this.actualTester = 1;
                this.labelTester.setText("Tester: 1");
                if (row + 1 == model.getRowCount()) {
                    JOptionPane.showMessageDialog(this, "Wszystkie próbki zostały przetestowane", null, JOptionPane.INFORMATION_MESSAGE);
                    this.model.setValueAt(String.format("%.2f", getAverageEvaluation(lastSelectedRow)), lastSelectedRow, model.getColumnCount()-1);
                } else {
                    this.table.setRowSelectionInterval(row + 1, row + 1);
                    getRowData();
                }
            } else {
                this.labelTester.setText("Tester: " + ++actualTester);
            }
        }
    }//GEN-LAST:event_buttonAcceptActionPerformed
/**
 * Akcja kliknięcia przycisku zapisu wyników. Pobiera z modelu tabeli dane w postaci ciągu znaków oddzielonych średnikami (.CSV).
 * @param evt Zdarzenie.
 */
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        try {
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd-HHmmss");
            String now = formatter.format(new Date());
            String path = new java.io.File(".").getCanonicalPath() + "\\RaportACR_" + now + ".csv";
            FileWriter fileWriter = new FileWriter(path);
            String result = model.getDataToSave();
            fileWriter.write(result);
            fileWriter.close();
            JOptionPane.showMessageDialog(this, "<html>Wyniki zapisano w pliku:<br>" + path + "</html>", null, JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "<html>Nie udało się zapisać wyników do pliku:<br>" + ex + "</html>", null, JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_buttonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccept;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTester;
    private javax.swing.JSlider sliderEvaluation;
    private javax.swing.JTable table;
    private javax.swing.JTextField textFieldSampleName;
    // End of variables declaration//GEN-END:variables
}
