/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soundtester;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Okno główne, zawierające główny panel programu (wybór testu, wczytywanie próbek, rozpoczęcie testu) oraz panel, do którego ładuje się dopowiedni podpanel, obsługujący wybrany rodzaj testu.
 */
public class View extends javax.swing.JFrame {

    /**
     * file chooser do wczytywania próbek
     */
    private JFileChooser fc;
    /**
     * lista próbek, w postaci ścieżek do plików
     */
    private ArrayList<String> samples;
    
    private View() {
        initComponents();
        setLocationRelativeTo(null);
        this.panelTest.setLayout(new BorderLayout());
        
        try {
            fc = new JFileChooser(new java.io.File(".").getCanonicalPath());
            fc.setMultiSelectionEnabled(true);
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        } catch (IOException ex) {
            fc = new JFileChooser();
            JOptionPane.showMessageDialog(this, ex, null, JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioButtonTest1 = new javax.swing.JRadioButton();
        radioButtonTest2 = new javax.swing.JRadioButton();
        radioButtonTest3 = new javax.swing.JRadioButton();
        buttonFileChooser = new javax.swing.JButton();
        textFieldInputPath = new javax.swing.JTextField();
        buttonStartTest = new javax.swing.JButton();
        spinnerTesters = new javax.swing.JSpinner();
        panelTest = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wybór testu"));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 100));

        buttonGroup1.add(radioButtonTest1);
        radioButtonTest1.setSelected(true);
        radioButtonTest1.setText("ACR"); // NOI18N

        buttonGroup1.add(radioButtonTest2);
        radioButtonTest2.setText("DCR"); // NOI18N

        buttonGroup1.add(radioButtonTest3);
        radioButtonTest3.setText("CCR"); // NOI18N

        buttonFileChooser.setText("Wybierz folder z próbkami (.wav)"); // NOI18N
        buttonFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileChooserActionPerformed(evt);
            }
        });

        textFieldInputPath.setEditable(false);
        textFieldInputPath.setMinimumSize(new java.awt.Dimension(6, 24));
        textFieldInputPath.setPreferredSize(new java.awt.Dimension(300, 24));

        buttonStartTest.setText("Rozpocznij test"); // NOI18N
        buttonStartTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartTestActionPerformed(evt);
            }
        });

        spinnerTesters.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spinnerTesters.setPreferredSize(new java.awt.Dimension(50, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radioButtonTest1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonTest2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonTest3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFileChooser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldInputPath, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerTesters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStartTest)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonTest1)
                    .addComponent(radioButtonTest2)
                    .addComponent(radioButtonTest3)
                    .addComponent(buttonFileChooser)
                    .addComponent(textFieldInputPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStartTest)
                    .addComponent(spinnerTesters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelTest.setBorder(javax.swing.BorderFactory.createTitledBorder("Test"));

        javax.swing.GroupLayout panelTestLayout = new javax.swing.GroupLayout(panelTest);
        panelTest.setLayout(panelTestLayout);
        panelTestLayout.setHorizontalGroup(
            panelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTestLayout.setVerticalGroup(
            panelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Akcja kliknięcia przycisku wczytania danych testowych. Otwierany jest file chooser, w celu wybrania katalogu z danymi testowymi (do testu DCR i CCR należy wybrać katalog, w którym próbki wzorcowe i testowe są obok siebie w kolejności: wzorzez, test).
 * @param evt Zdarzenie.
 */
    private void buttonFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileChooserActionPerformed
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.textFieldInputPath.setText(fc.getSelectedFile().getAbsolutePath());
            this.textFieldInputPath.setToolTipText(fc.getSelectedFile().getAbsolutePath());
            
            if (this.samples == null) {
                this.samples = new ArrayList<>();
            } else {
                this.samples.clear();
            }
            
            String filePath;
            File directory = fc.getSelectedFile();
            if (directory != null && directory.isDirectory()) {
                for (File subFile : directory.listFiles()) {
                    filePath = subFile.getAbsolutePath();
                    if (filePath.endsWith(".wav")) {
                        this.samples.add(filePath);
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Wczytanych próbek (.wav): " + this.samples.size(), null, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonFileChooserActionPerformed
/**
 * Akcja kliknięcia przycisku, który rozpoczyna wybrany test (odpowiedni radio button). Ładowany jest panel obsługujący dany test, a do jego tabeli wczytywane są dane na podstawie wczytanych próbek.
 * @param evt Zdarzenie.
 */
    private void buttonStartTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartTestActionPerformed
        String inputPath = textFieldInputPath.getText().trim();
        if (inputPath == null || inputPath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nie podano ścieżki do folderu z próbkami", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (this.samples.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lista wczytanych próbek jest pusta", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.panelTest.removeAll();
        if (radioButtonTest1.isSelected()) {
            this.panelTest.add(new PanelACR(samples, (Integer) this.spinnerTesters.getValue()));
        } else if (radioButtonTest2.isSelected()) {
            this.panelTest.add(new PanelDCR(samples, (Integer) this.spinnerTesters.getValue(), false));
        } else if (radioButtonTest3.isSelected()) {
            this.panelTest.add(new PanelDCR(samples, (Integer) this.spinnerTesters.getValue(), true));
        }
        this.panelTest.revalidate();
        this.panelTest.repaint();
    }//GEN-LAST:event_buttonStartTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFileChooser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonStartTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelTest;
    private javax.swing.JRadioButton radioButtonTest1;
    private javax.swing.JRadioButton radioButtonTest2;
    private javax.swing.JRadioButton radioButtonTest3;
    private javax.swing.JSpinner spinnerTesters;
    private javax.swing.JTextField textFieldInputPath;
    // End of variables declaration//GEN-END:variables
}
